title: <p style="font-size:30px"> Blacksheep Music Collective
author: Bennington People
email: elizeltzer@bennington.edu
description: > # this means to ignore newlines until "baseurl:"
  Site for Intro to Javascript, Bennington College, Fall 2016
baseurl: "/minima"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
