title:  Blacksheep Music Collective
author: Eli Zeltzer
email: elizeltzer@bennington.edu
description: > # this means to ignore newlines until "baseurl:"
  Site for Intro to Javascript, Bennington College, Fall 2016
baseurl: "/minima"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
